### ISSUE TITLE
runtime error when idexing the fasta file

### ISSUE THREAD

**Issue by sunrisewestern** [quwubin/MFEprimer-3.0#16]
When running `mfeprimer index -i hs37d5.fa` get the following error

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/quwubin/mfeprimer/cmd.write2DB({0xc00001e0d8, 0x14}, {0x0, 0x0, 0x4?}, {0x0, 0x0, 0x43adc20?}, 0x40000)
	/Users/quwb/quwubin/mfeprimer/cmd/index.go:591 +0x645
github.com/quwubin/mfeprimer/cmd.makeIndex({0x2087ae853, 0xb}, 0x9, 0x10, 0x4c4b40, 0x4051800000000000, 0x0)
	/Users/quwb/quwubin/mfeprimer/cmd/index.go:330 +0x6d8
github.com/quwubin/mfeprimer/cmd.glob..func4(0x43a8de0?, {0xc000148420?, 0x2?, 0x2?})
	/Users/quwb/quwubin/mfeprimer/cmd/index.go:65 +0x265
github.com/spf13/cobra.(*Command).execute(0x43a8de0, {0xc000148400, 0x2, 0x2})
	/Users/quwb/gocode/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x43a9560)
	/Users/quwb/gocode/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/quwb/gocode/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/quwubin/mfeprimer/cmd.Execute()
	/Users/quwb/quwubin/mfeprimer/cmd/root.go:576 +0x25
main.main()
	/Users/quwb/quwubin/mfeprimer/main.go:10 +0x17
```

Already tried to split the fasta file into several 1GB files, but still got the error.

**Comment by quwubin** [comment]
It seems that there is a blank sequence in the database. Please check the database.
